#if UNITY_EDITOR

using UnityEngine;
using UnityEditor;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections.Generic;
using _Car_Parking.Scripts.SOAP;

public static class EventRegistryKeyGenerator
{
    public static void Generate(EventRegistry registry)
    {
        if (!registry)
            return;

        // 1. Validate asset
        if (string.IsNullOrEmpty(AssetDatabase.GetAssetPath(registry)))
            return;

        string assetName = registry.name;

        // 2. Create the Class Name
        string sanitizedAssetName = Regex.Replace(assetName, @"[^a-zA-Z0-9_]", "");
        string className = $"{sanitizedAssetName}IDs";
        className = className.Replace("_", "");

        // 3. Determine Output Path — same folder as GameInputManager.cs
        string folderPath = null;
        foreach (string guid in AssetDatabase.FindAssets("GameInputManager t:MonoScript"))
        {
            string p = AssetDatabase.GUIDToAssetPath(guid);
            if (p.EndsWith("GameInputManager.cs"))
            {
                folderPath = Path.GetDirectoryName(p);
                break;
            }
        }

        if (folderPath == null)
        {
            Debug.LogError("[EventRegistry] Could not find GameInputManager.cs in project.");
            return;
        }

        string fullPath = Path.Combine(folderPath, $"{className}.cs");

        // 4. Generate Content
        SerializedObject so = new SerializedObject(registry);
        SerializedProperty regionsProp = so.FindProperty("entryRegions");

        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// THIS FILE IS AUTO-GENERATED by EventRegistryKeyGenerator.cs");
        sb.AppendLine($"// Generated from asset: {assetName}");
        sb.AppendLine("namespace _Car_Parking.Scripts.SOAP");
        sb.AppendLine("{");
        sb.AppendLine($"    public static class {className}");
        sb.AppendLine("    {");

        HashSet<string> generatedVarNames = new HashSet<string>();

        if (regionsProp != null && regionsProp.isArray)
        {
            for (int i = 0; i < regionsProp.arraySize; i++)
            {
                SerializedProperty region = regionsProp.GetArrayElementAtIndex(i);
                SerializedProperty entriesProp = region.FindPropertyRelative("entries");

                if (entriesProp == null || !entriesProp.isArray)
                    continue;

                for (int j = 0; j < entriesProp.arraySize; j++)
                {
                    SerializedProperty entry = entriesProp.GetArrayElementAtIndex(j);
                    string id = entry.FindPropertyRelative("ID").stringValue;

                    if (string.IsNullOrWhiteSpace(id)) continue;

                    string varName = Regex.Replace(id, "[^a-zA-Z0-9_]", "_");
                    if (char.IsDigit(varName[0]))
                        varName = "_" + varName;

                    if (varName.Length > 0 && char.IsLower(varName[0]))
                        varName = char.ToUpper(varName[0]) + varName.Substring(1);

                    if (!generatedVarNames.Add(varName))
                        continue;

                    sb.AppendLine($"        public const string {varName} = \"{id}\";");
                }
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        // 5. Write File
        try
        {
            if (File.Exists(fullPath) && File.ReadAllText(fullPath) == sb.ToString())
                return;

            File.WriteAllText(fullPath, sb.ToString());
            EditorApplication.delayCall += AssetDatabase.Refresh;
            Debug.Log($"[EventRegistry] Generated {className}.cs with {generatedVarNames.Count} keys.");
        }
        catch (IOException e)
        {
            Debug.LogError($"[EventRegistry] Failed to write file: {e.Message}");
        }
    }
}
#endif