// Reads EventRegistry entries and FULLY REWRITES GameInputEvents.cs
#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;
using _Car_Parking.Scripts.SOAP;

namespace _Car_Parking.Scripts.GameInput.Editor
{
    [CustomEditor(typeof(EventRegistry))]
    public class EventRegistryWithEventsEditor : UnityEditor.Editor
    {
        public override void OnInspectorGUI()
        {
            EventRegistry registry = (EventRegistry)target;

            bool autoOn  = EditorPrefs.GetBool(GameInputEventsGenerator.PrefAuto, false);
            bool newAuto = EditorGUILayout.ToggleLeft("Auto-refresh GameInputEvents on save", autoOn);
            if (newAuto != autoOn)
                EditorPrefs.SetBool(GameInputEventsGenerator.PrefAuto, newAuto);

            EditorGUILayout.Space(4);
            if (GUILayout.Button("Regenerate GameInputEvents", GUILayout.Height(28)))
                GameInputEventsGenerator.Generate(registry);

            EditorGUILayout.Space(4);
            if (GUILayout.Button($"Regenerate {registry.name}IDs Class", GUILayout.Height(28)))
                EventRegistryKeyGenerator.Generate(registry);

            EditorGUILayout.Space(6);
            base.OnInspectorGUI();
        }
    }

    public static class GameInputEventsGenerator
    {
        public  const string PrefAuto          = "GIG_AutoEvents";
        private const string Namespace         = "_Car_Parking.Scripts.GameInput";
        private const string SoapNs            = "_Car_Parking.Scripts.SOAP";
        private const string RegistryIDsClass  = "EventRegistryIDs";

        private static string OutputPath =>
            "Assets/_Car Parking/Scripts/GameInput/GameInputEvents.cs";

        [MenuItem("CPMInstruments/Game Input/Regenerate GameInputEvents")]
        public static void GenerateFromMenu()
        {
            var asset = FindAsset();
            if (asset == null)
            {
                Debug.LogError("[EventsGen] No EventRegistry asset found in project.");
                return;
            }
            Generate(asset);
        }

        [MenuItem("CPMInstruments/Game Input/Toggle Auto-refresh: GameInputEvents")]
        public static void ToggleAutoRefresh()
        {
            bool next = !EditorPrefs.GetBool(PrefAuto, false);
            EditorPrefs.SetBool(PrefAuto, next);
            Debug.Log($"[EventsGen] Auto-refresh set to: {next}");
        }

        [MenuItem("CPMInstruments/Game Input/Toggle Auto-refresh: GameInputEvents", true)]
        public static bool ValidateToggle()
        {
            Menu.SetChecked("CPMInstruments/Game Input/Toggle Auto-refresh: GameInputEvents",
                EditorPrefs.GetBool(PrefAuto, false));
            return true;
        }

        public static void Generate(EventRegistry registry)
        {
            var so          = new SerializedObject(registry);
            var regionsProp = so.FindProperty("entryRegions");
            if (regionsProp == null)
            {
                Debug.LogError("[EventsGen] Could not find 'entryRegions' on EventRegistry.");
                return;
            }

            var handles    = new List<(string handleT, string fieldName, string constName)>();
            var seenFields = new HashSet<string>();

            for (int i = 0; i < regionsProp.arraySize; i++)
            {
                var region = regionsProp.GetArrayElementAtIndex(i);
                var isUsed = region.FindPropertyRelative("isUsed");
                if (isUsed != null && !isUsed.boolValue) continue;

                var entriesProp = region.FindPropertyRelative("entries");
                if (entriesProp == null) continue;

                for (int j = 0; j < entriesProp.arraySize; j++)
                {
                    var    entry    = entriesProp.GetArrayElementAtIndex(j);
                    string id       = entry.FindPropertyRelative("ID").stringValue;
                    var    assetRef = entry.FindPropertyRelative("Asset").objectReferenceValue;

                    if (string.IsNullOrWhiteSpace(id) || assetRef == null) continue;

                    string handleT   = GetHandleType(assetRef.GetType().Name);
                    string fieldName = ToFieldName(id);
                    string constName = SanitizeConst(id);

                    string unique = fieldName;
                    int    suffix = 2;
                    while (!seenFields.Add(unique))
                        unique = fieldName.Replace("Handle", "") + suffix++ + "Handle";

                    handles.Add((handleT, unique, constName));
                }
            }

            var sb = new StringBuilder();
            sb.AppendLine("// THIS FILE IS AUTO-GENERATED by GameInputEventsGenerator.cs");
            sb.AppendLine($"using {SoapNs};");
            sb.AppendLine();
            sb.AppendLine($"namespace {Namespace}");
            sb.AppendLine("{");
            sb.AppendLine("    public partial class GameInputManager");
            sb.AppendLine("    {");
            sb.AppendLine("        private InputMapSetEvent _inputMapSetEvent;");
            sb.AppendLine();
            foreach (var (handleT, fieldName, constName) in handles)
                sb.AppendLine($"        private RegistryHandle<{handleT}> {fieldName} = new ({RegistryIDsClass}.{constName});");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            string fullPath = Path.GetFullPath(OutputPath);
            Directory.CreateDirectory(Path.GetDirectoryName(fullPath)!);

            if (File.Exists(fullPath) && File.ReadAllText(fullPath) == sb.ToString())
            {
                Debug.Log("[EventsGen] No changes.");
                return;
            }

            File.WriteAllText(fullPath, sb.ToString());
            EditorApplication.delayCall += AssetDatabase.Refresh;
            Debug.Log($"[EventsGen] GameInputEvents.cs rewritten with {handles.Count} handle(s).");
        }

        private static string GetHandleType(string typeName) => typeName switch
        {
            "BoolEvent"       => "BoolEvent",
            "FloatVariable"   => "FloatVariable",
            "Vector2Variable" => "Vector2Variable",
            "Vector3Variable" => "Vector3Variable",
            "IntVariable"     => "IntVariable",
            "StringVariable"  => "StringVariable",
            _                 => "ScriptableEvent",
        };

        // "OpenPhone" → "_openPhoneHandle", "ON_MENU" → "_onMenuHandle"
        private static string ToFieldName(string id)
        {
            var  parts = Regex.Split(id, @"[^a-zA-Z0-9]+");
            var  sb    = new StringBuilder("_");
            bool first = true;
            foreach (string part in parts)
            {
                if (part.Length == 0) continue;
                if (first) { sb.Append(char.ToLower(part[0])); sb.Append(part.Substring(1)); first = false; }
                else       { sb.Append(char.ToUpper(part[0])); sb.Append(part.Substring(1)); }
            }
            sb.Append("Handle");
            return sb.ToString();
        }

        private static string SanitizeConst(string id)
        {
            string v = Regex.Replace(id, "[^a-zA-Z0-9_]", "_");
            if (char.IsDigit(v[0])) v = "_" + v;
            if (char.IsLower(v[0])) v = char.ToUpper(v[0]) + v.Substring(1);
            return v;
        }

        private static EventRegistry FindAsset()
        {
            string[] guids = AssetDatabase.FindAssets("t:EventRegistry");
            if (guids.Length == 0) return null;
            return AssetDatabase.LoadAssetAtPath<EventRegistry>(
                AssetDatabase.GUIDToAssetPath(guids[0]));
        }

        private class AutoRefreshPostprocessor : AssetPostprocessor
        {
            private static void OnPostprocessAllAssets(
                string[] imported, string[] _d, string[] _m, string[] _mf)
            {
                if (!EditorPrefs.GetBool(PrefAuto, false)) return;
                foreach (string path in imported)
                {
                    var asset = AssetDatabase.LoadAssetAtPath<EventRegistry>(path);
                    if (asset != null)
                    {
                        EditorApplication.delayCall += () => Generate(asset);
                        return;
                    }
                }
            }
        }
    }
}
#endif