// THIS FILE IS AUTO-GENERATED by EventRegistryKeyGenerator.cs
// Generated from asset: _EventRegistry
namespace _Car_Parking.Scripts.SOAP
{
    public static class EventRegistryIDs
    {
        public const string OpenPhone = "openPhone";
        public const string OnMenu = "onMenu";
        public const string OnThrottle = "onThrottle";
        public const string OnStartEngine = "onStartEngine";
        public const string OnLook = "onLook";
        public const string Cancel = "cancel";
        public const string ChangeCamera = "changeCamera";
        public const string ToggleMap = "toggleMap";
        public const string CircleMenu = "circleMenu";
        public const string CircleMenuScroll = "circleMenuScroll";
        public const string CloseCircleMenu = "closeCircleMenu";
        public const string DoorStartCancel = "doorStartCancel";
        public const string ShifterUpDown = "shifterUpDown";
        public const string ShifterMA = "shifterMA";
        public const string ShifterMoveStarted = "shifterMoveStarted";
        public const string ShiftToggleMA = "shiftToggleMA";
        public const string OnHorn = "onHorn";
        public const string OnHeadlights = "onHeadlights";
        public const string Throttle = "throttle";
        public const string Brake = "brake";
        public const string Clutch = "clutch";
        public const string Steer = "steer";
        public const string Handbrake = "handbrake";
        public const string Zoom = "zoom";
        public const string Look = "look";
        public const string MovePerson = "movePerson";
        public const string MapMove = "mapMove";
        public const string CircleMenuMove = "circleMenuMove";
        public const string ShifterMove = "shifterMove";
        public const string SetActionsActive = "setActionsActive";
        public const string OnNextPrevious = "onNextPrevious";
        public const string OnLayerUpDown = "onLayerUpDown";
        public const string OnNavigateExisting = "onNavigateExisting";
        public const string OnNavigateNew = "onNavigateNew";
        public const string ToggleToSize = "toggleToSize";
        public const string ToggleToColor = "toggleToColor";
        public const string AddFavorite = "addFavorite";
        public const string Copy = "copy";
        public const string DeleteAll = "deleteAll";
        public const string DeleteSelected = "deleteSelected";
        public const string Mirror = "mirror";
        public const string SetColor = "setColor";
        public const string SetSize = "setSize";
        public const string BlockCamera = "blockCamera";
        public const string ToggleFavorites = "toggleFavorites";
        public const string ToggleMultiSelect = "toggleMultiSelect";
        public const string ToggleUi = "toggleUi";
        public const string OpacityChange = "opacityChange";
        public const string TurnLeftRight = "turnLeftRight";
        public const string ColorChange = "colorChange";
        public const string SizeChange = "sizeChange";
        public const string PositionChange = "positionChange";
        public const string OnApplyChanges = "onApplyChanges";
        public const string OnCancelChanges = "onCancelChanges";
        public const string OnStartColorMove = "onStartColorMove";
        public const string OnStartTintMove = "onStartTintMove";
    }
}
