// THIS FILE IS AUTO-GENERATED by GameInputEventsGenerator.cs
using _Car_Parking.Scripts.SOAP;

namespace _Car_Parking.Scripts.GameInput
{
    public partial class GameInputManager
    {
        private InputMapSetEvent _inputMapSetEvent;

        private RegistryHandle<ScriptableEvent> _openPhoneHandle = new (EventRegistryIDs.OpenPhone);
        private RegistryHandle<ScriptableEvent> _onMenuHandle = new (EventRegistryIDs.OnMenu);
        private RegistryHandle<BoolEvent> _onThrottleHandle = new (EventRegistryIDs.OnThrottle);
        private RegistryHandle<BoolEvent> _onStartEngineHandle = new (EventRegistryIDs.OnStartEngine);
        private RegistryHandle<BoolEvent> _onLookHandle = new (EventRegistryIDs.OnLook);
        private RegistryHandle<ScriptableEvent> _cancelHandle = new (EventRegistryIDs.Cancel);
        private RegistryHandle<ScriptableEvent> _changeCameraHandle = new (EventRegistryIDs.ChangeCamera);
        private RegistryHandle<BoolEvent> _toggleMapHandle = new (EventRegistryIDs.ToggleMap);
        private RegistryHandle<BoolEvent> _circleMenuHandle = new (EventRegistryIDs.CircleMenu);
        private RegistryHandle<BoolEvent> _circleMenuScrollHandle = new (EventRegistryIDs.CircleMenuScroll);
        private RegistryHandle<ScriptableEvent> _closeCircleMenuHandle = new (EventRegistryIDs.CloseCircleMenu);
        private RegistryHandle<BoolEvent> _doorStartCancelHandle = new (EventRegistryIDs.DoorStartCancel);
        private RegistryHandle<BoolEvent> _shifterUpDownHandle = new (EventRegistryIDs.ShifterUpDown);
        private RegistryHandle<BoolEvent> _shifterMAHandle = new (EventRegistryIDs.ShifterMA);
        private RegistryHandle<BoolEvent> _shifterMoveStartedHandle = new (EventRegistryIDs.ShifterMoveStarted);
        private RegistryHandle<ScriptableEvent> _shiftToggleMAHandle = new (EventRegistryIDs.ShiftToggleMA);
        private RegistryHandle<BoolEvent> _onHornHandle = new (EventRegistryIDs.OnHorn);
        private RegistryHandle<ScriptableEvent> _onHeadlightsHandle = new (EventRegistryIDs.OnHeadlights);
        private RegistryHandle<FloatVariable> _throttleHandle = new (EventRegistryIDs.Throttle);
        private RegistryHandle<FloatVariable> _brakeHandle = new (EventRegistryIDs.Brake);
        private RegistryHandle<FloatVariable> _clutchHandle = new (EventRegistryIDs.Clutch);
        private RegistryHandle<FloatVariable> _steerHandle = new (EventRegistryIDs.Steer);
        private RegistryHandle<FloatVariable> _handbrakeHandle = new (EventRegistryIDs.Handbrake);
        private RegistryHandle<FloatVariable> _zoomHandle = new (EventRegistryIDs.Zoom);
        private RegistryHandle<Vector2Variable> _lookHandle = new (EventRegistryIDs.Look);
        private RegistryHandle<Vector2Variable> _movePersonHandle = new (EventRegistryIDs.MovePerson);
        private RegistryHandle<Vector3Variable> _mapMoveHandle = new (EventRegistryIDs.MapMove);
        private RegistryHandle<Vector2Variable> _circleMenuMoveHandle = new (EventRegistryIDs.CircleMenuMove);
        private RegistryHandle<Vector2Variable> _shifterMoveHandle = new (EventRegistryIDs.ShifterMove);
        private RegistryHandle<BoolEvent> _setActionsActiveHandle = new (EventRegistryIDs.SetActionsActive);
        private RegistryHandle<BoolEvent> _onNextPreviousHandle = new (EventRegistryIDs.OnNextPrevious);
        private RegistryHandle<BoolEvent> _onLayerUpDownHandle = new (EventRegistryIDs.OnLayerUpDown);
        private RegistryHandle<BoolEvent> _onNavigateExistingHandle = new (EventRegistryIDs.OnNavigateExisting);
        private RegistryHandle<BoolEvent> _onNavigateNewHandle = new (EventRegistryIDs.OnNavigateNew);
        private RegistryHandle<ScriptableEvent> _toggleToSizeHandle = new (EventRegistryIDs.ToggleToSize);
        private RegistryHandle<ScriptableEvent> _toggleToColorHandle = new (EventRegistryIDs.ToggleToColor);
        private RegistryHandle<ScriptableEvent> _addFavoriteHandle = new (EventRegistryIDs.AddFavorite);
        private RegistryHandle<ScriptableEvent> _copyHandle = new (EventRegistryIDs.Copy);
        private RegistryHandle<ScriptableEvent> _deleteAllHandle = new (EventRegistryIDs.DeleteAll);
        private RegistryHandle<ScriptableEvent> _deleteSelectedHandle = new (EventRegistryIDs.DeleteSelected);
        private RegistryHandle<ScriptableEvent> _mirrorHandle = new (EventRegistryIDs.Mirror);
        private RegistryHandle<ScriptableEvent> _setColorHandle = new (EventRegistryIDs.SetColor);
        private RegistryHandle<ScriptableEvent> _setSizeHandle = new (EventRegistryIDs.SetSize);
        private RegistryHandle<ScriptableEvent> _blockCameraHandle = new (EventRegistryIDs.BlockCamera);
        private RegistryHandle<ScriptableEvent> _toggleFavoritesHandle = new (EventRegistryIDs.ToggleFavorites);
        private RegistryHandle<ScriptableEvent> _toggleMultiSelectHandle = new (EventRegistryIDs.ToggleMultiSelect);
        private RegistryHandle<ScriptableEvent> _toggleUiHandle = new (EventRegistryIDs.ToggleUi);
        private RegistryHandle<FloatVariable> _opacityChangeHandle = new (EventRegistryIDs.OpacityChange);
        private RegistryHandle<FloatVariable> _turnLeftRightHandle = new (EventRegistryIDs.TurnLeftRight);
        private RegistryHandle<Vector2Variable> _colorChangeHandle = new (EventRegistryIDs.ColorChange);
        private RegistryHandle<Vector2Variable> _sizeChangeHandle = new (EventRegistryIDs.SizeChange);
        private RegistryHandle<Vector2Variable> _positionChangeHandle = new (EventRegistryIDs.PositionChange);
        private RegistryHandle<ScriptableEvent> _onApplyChangesHandle = new (EventRegistryIDs.OnApplyChanges);
        private RegistryHandle<ScriptableEvent> _onCancelChangesHandle = new (EventRegistryIDs.OnCancelChanges);
        private RegistryHandle<ScriptableEvent> _onStartColorMoveHandle = new (EventRegistryIDs.OnStartColorMove);
        private RegistryHandle<ScriptableEvent> _onStartTintMoveHandle = new (EventRegistryIDs.OnStartTintMove);
    }
}
