// THIS FILE IS AUTO-GENERATED by GameInputMapGenerator.cs
using _Car_Parking.Scripts.Other.Helpers;

namespace _Car_Parking.Scripts.GameInput
{
    public partial class GameInputManager
    {
        private void ToggleMap(InputMapEnum inputMap, bool toggleOn)
        {
            switch (inputMap)
            {
                case InputMapEnum.UI:
                    if (toggleOn) _controls.UI.Enable(); else _controls.UI.Disable();
                    break;
                case InputMapEnum.UIAcceptCancel:
                    if (toggleOn) _controls.UIAcceptCancel.Enable(); else _controls.UIAcceptCancel.Disable();
                    break;
                case InputMapEnum.UiPointer:
                    if (toggleOn) _controls.UiPointer.Enable(); else _controls.UiPointer.Disable();
                    break;
                case InputMapEnum.UiNextPrevious:
                    if (toggleOn) _controls.UiNextPrevious.Enable(); else _controls.UiNextPrevious.Disable();
                    break;
                case InputMapEnum.UiThrottle:
                    if (toggleOn) _controls.UiThrottle.Enable(); else _controls.UiThrottle.Disable();
                    break;
                case InputMapEnum.Menu:
                    if (toggleOn) _controls.Menu.Enable(); else _controls.Menu.Disable();
                    break;
                case InputMapEnum.ShowMap:
                    if (toggleOn) _controls.ShowMap.Enable(); else _controls.ShowMap.Disable();
                    break;
                case InputMapEnum.SlotManager:
                    if (toggleOn) _controls.SlotManager.Enable(); else _controls.SlotManager.Disable();
                    break;
                case InputMapEnum.MapUi:
                    if (toggleOn) _controls.MapUi.Enable(); else _controls.MapUi.Disable();
                    break;
                case InputMapEnum.Drone:
                    if (toggleOn) _controls.Drone.Enable(); else _controls.Drone.Disable();
                    break;
                case InputMapEnum.DroneCamera:
                    if (toggleOn) _controls.DroneCamera.Enable(); else _controls.DroneCamera.Disable();
                    break;
                case InputMapEnum.Photo:
                    if (toggleOn) _controls.Photo.Enable(); else _controls.Photo.Disable();
                    break;
                case InputMapEnum.PaintBase:
                    if (toggleOn) _controls.PaintBase.Enable(); else _controls.PaintBase.Disable();
                    break;
                case InputMapEnum.PaintApplyCancel:
                    if (toggleOn) _controls.PaintApplyCancel.Enable(); else _controls.PaintApplyCancel.Disable();
                    break;
                case InputMapEnum.PaintMultiSelect:
                    if (toggleOn) _controls.PaintMultiSelect.Enable(); else _controls.PaintMultiSelect.Disable();
                    break;
                case InputMapEnum.PaintSelectNew:
                    if (toggleOn) _controls.PaintSelectNew.Enable(); else _controls.PaintSelectNew.Disable();
                    break;
                case InputMapEnum.PaintSelectSet:
                    if (toggleOn) _controls.PaintSelectSet.Enable(); else _controls.PaintSelectSet.Disable();
                    break;
                case InputMapEnum.PaintCopy:
                    if (toggleOn) _controls.PaintCopy.Enable(); else _controls.PaintCopy.Disable();
                    break;
                case InputMapEnum.PaintFavorite:
                    if (toggleOn) _controls.PaintFavorite.Enable(); else _controls.PaintFavorite.Disable();
                    break;
                case InputMapEnum.PaintSelectionMade:
                    if (toggleOn) _controls.PaintSelectionMade.Enable(); else _controls.PaintSelectionMade.Disable();
                    break;
                case InputMapEnum.PaintColor:
                    if (toggleOn) _controls.PaintColor.Enable(); else _controls.PaintColor.Disable();
                    break;
                case InputMapEnum.PaintSize:
                    if (toggleOn) _controls.PaintSize.Enable(); else _controls.PaintSize.Disable();
                    break;
                case InputMapEnum.Camera:
                    if (toggleOn) _controls.Camera.Enable(); else _controls.Camera.Disable();
                    break;
                case InputMapEnum.CameraGarage:
                    if (toggleOn) _controls.CameraGarage.Enable(); else _controls.CameraGarage.Disable();
                    break;
                case InputMapEnum.ChangeCamera:
                    if (toggleOn) _controls.ChangeCamera.Enable(); else _controls.ChangeCamera.Disable();
                    break;
                case InputMapEnum.CarRacing:
                    if (toggleOn) _controls.CarRacing.Enable(); else _controls.CarRacing.Disable();
                    break;
                case InputMapEnum.CarDrag:
                    if (toggleOn) _controls.CarDrag.Enable(); else _controls.CarDrag.Disable();
                    break;
                case InputMapEnum.Headlights:
                    if (toggleOn) _controls.Headlights.Enable(); else _controls.Headlights.Disable();
                    break;
                case InputMapEnum.Door:
                    if (toggleOn) _controls.Door.Enable(); else _controls.Door.Disable();
                    break;
                case InputMapEnum.PhoneVoice:
                    if (toggleOn) _controls.PhoneVoice.Enable(); else _controls.PhoneVoice.Disable();
                    break;
                case InputMapEnum.CircleMenu:
                    if (toggleOn) _controls.CircleMenu.Enable(); else _controls.CircleMenu.Disable();
                    break;
                case InputMapEnum.OpenCircleMenu:
                    if (toggleOn) _controls.OpenCircleMenu.Enable(); else _controls.OpenCircleMenu.Disable();
                    break;
                case InputMapEnum.CarBase:
                    if (toggleOn) _controls.CarBase.Enable(); else _controls.CarBase.Disable();
                    break;
                case InputMapEnum.Shifter:
                    if (toggleOn) _controls.Shifter.Enable(); else _controls.Shifter.Disable();
                    break;
                case InputMapEnum.Person:
                    if (toggleOn) _controls.Person.Enable(); else _controls.Person.Disable();
                    break;
                default:
                    WDebug.LogError($"[GameInputManager] Unhandled InputMapEnum: {inputMap}");
                    break;
            }
        }
    }
}
