// THIS FILE IS AUTO-GENERATED by GameInputMapGenerator.cs
namespace _Car_Parking.Scripts.GameInput
{
    [System.Serializable]
    public enum InputMapEnum // actual input maps in GameInputController
    {
        None = 0,
        UI = 1,
        UiNextPrevious = 2,
        UiThrottle = 3,
        Menu = 4,
        ShowMap = 5,
        SlotManager = 6,
        MapUi = 7,
        Drone = 8,
        Photo = 10,
        Door = 11,
        Camera = 12,
        CameraGarage = 13,
        ChangeCamera = 14,
        UIAcceptCancel = 15,
        CarRacing = 16,
        CarDrag = 17,
        Headlights = 18,
        CircleMenu = 19,
        CarBase = 20,
        Person = 21,
        DroneCamera = 22,
        PhoneVoice = 23,
        PaintBase = 25,
        PaintApplyCancel = 26,
        PaintMultiSelect = 27,
        PaintSelectNew = 28,
        PaintSelectSet = 29,
        PaintCopy = 30,
        PaintFavorite = 31,
        PaintSelectionMade = 32,
        PaintColor = 33,
        PaintSize = 34,
        UiPointer = 35,
        OpenCircleMenu = 36,
        Shifter = 37,
    }
}
